"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";
import SiteHeader from "@/components/SiteHeader";
const supabase=createClient();
export default function PublicUserPage(){
 const [p,setP]=useState<any>(null),[ss,setSs]=useState<any[]>([]),[rr,setRr]=useState<any[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const id=new URLSearchParams(window.location.search).get("id");if(!id){setLoading(false);return}const [{data:profile},{data:services},{data:reviews}]=await Promise.all([supabase.from("profiles").select("id,display_name,bio,city,region,district").eq("id",id).maybeSingle(),supabase.from("services").select("id,title,description,price,price_type,city,region").eq("user_id",id).eq("status","published").order("created_at",{ascending:false}),supabase.from("reviews").select("id,author_id,rating,body,created_at").eq("target_user_id",id).order("created_at",{ascending:false})]);setP(profile);setSs(services||[]);const ids=[...new Set((reviews||[]).map((r:any)=>r.author_id))];let names:Record<string,string>={};if(ids.length){const {data:ps}=await supabase.from("profiles").select("id,display_name").in("id",ids);names=Object.fromEntries((ps||[]).map((x:any)=>[x.id,x.display_name||"Пользователь"]))}setRr((reviews||[]).map((r:any)=>({...r,author_name:names[r.author_id]||"Пользователь"})));setLoading(false)})()},[]);
 if(loading)return <><SiteHeader/><main className="page-shell"><div className="empty-state">Загрузка профиля…</div></main></>;if(!p)return <><SiteHeader/><main className="page-shell"><div className="empty-state"><h3>Профиль не найден</h3><Link href="/services">Вернуться в каталог</Link></div></main>;
 const avg=rr.length?(rr.reduce((a,r)=>a+r.rating,0)/rr.length).toFixed(1):null;
 return <><SiteHeader/><main className="page-shell public-profile-page"><div className="breadcrumbs"><Link href="/services">Каталог</Link><span>/</span><span>Профиль исполнителя</span></div><section className="public-profile-hero"><div className="public-avatar">{(p.display_name||"П").slice(0,1).toUpperCase()}</div><div><span className="eyebrow">Исполнитель</span><h1>{p.display_name||"Пользователь"}</h1><p>{[p.city,p.region].filter(Boolean).join(" · ")||"Локация не указана"}</p></div>{avg&&<div className="public-rating"><strong>{avg}</strong><span>★ · {rr.length} отзывов</span></div>}</section><div className="public-profile-grid"><section className="content-card"><span className="eyebrow">О специалисте</span><h2>{p.bio||"Специалист пока не добавил описание."}</h2><p className="muted">{p.district?("Район: "+p.district):"Работает с заказчиками через Услугач."}</p></section><section className="content-card"><span className="eyebrow">Услуги</span><h2>Предложения специалиста</h2>{ss.length?<div className="public-service-list">{ss.map(s=><Link className="public-service-item" href={"/service?id="+s.id} key={s.id}><div><strong>{s.title}</strong><span>{s.city||s.region||"Онлайн"}</span></div><b>{s.price==null?"По договорённости":new Intl.NumberFormat("ru-RU").format(s.price)+" ₽"}</b></Link>)}</div>:<div className="mini-empty">Опубликованных услуг пока нет.</div>}</section></div>{rr.length>0&&<section className="service-reviews public-reviews"><span className="eyebrow">Отзывы</span><h2>Что говорят клиенты</h2><div className="review-list">{rr.map(r=><article className="review-card" key={r.id}><div className="review-card-head"><div className="avatar">{r.author_name.slice(0,1).toUpperCase()}</div><div><strong>{r.author_name}</strong><small>{new Date(r.created_at).toLocaleDateString("ru-RU")}</small></div><span className="review-rating">{"★".repeat(r.rating)}<i>{"★".repeat(5-r.rating)}</i></span></div>{r.body&&<p>{r.body}</p>}</article>)}</div></section>}</main></>}